### ISSUE TITLE
DesignManager [initial]

### ISSUE THREAD

**Issue by ArsenijSerjogin** [ArsenijSerjogin/TagExplorere#3]
Class need for getting theme parameters, select other themes or customize/create new (will in future).

- [ ] Implement reading of [first theme](https://github.com/ArsenijSerjogin/TagExplorere/issues/1)
    - [ ] Read from [settings file](https://github.com/ArsenijSerjogin/TagExplorere/issues/2) current theme
    - [ ] Load colorPalette from currentTheme
- [ ] Read all themes name from themes folder to themesNameList
- [ ] Implement writing of new selected theme to [settings file](https://github.com/ArsenijSerjogin/TagExplorere/issues/2)
