### ISSUE TITLE
1. Theme [initial]

### ISSUE THREAD

**Issue by ArsenijSerjogin** [ArsenijSerjogin/TagExplorere#6]
### Themes
Application need read theme settings for unification color palette or other visual function in project.
Each themes need save to individual file.
Need application settings file, where will saved current selected theme.
For start can be only one theme.
### For that:
- [ ] Find what need to [take out to theme](https://github.com/ArsenijSerjogin/TagExplorere/issues/1)
- [ ] Create application [settings file](https://github.com/ArsenijSerjogin/TagExplorere/issues/2)
- [ ] Create class ["DesignManager"](https://github.com/ArsenijSerjogin/TagExplorere/issues/3)
- [ ] [Load](https://github.com/ArsenijSerjogin/TagExplorere/issues/4) from them "colorPalette"
- [ ] Implement [selection of theme](https://github.com/ArsenijSerjogin/TagExplorere/issues/5)
